# Generated by Django 4.2.7 on 2024-02-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_sli'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sli',
        ),
    ]
